### ISSUE TITLE
[llvm] Add support for optimizing for runtime

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#370]
## 🚀 Feature

This is a tracking issue for work related to adding support for optimizing the LLVM environments for minimizing runtime.

## Progress

- [x] Initial proof-of-concept for `benchmark://cbench-v0` and `generator://csmith-v0` datasets ([#307](https://github.com/facebookresearch/CompilerGym/pull/307)).
- [x] Document the new observation spaces ([#373](https://github.com/facebookresearch/CompilerGym/pull/373)).
- [x] Add a `MutexReward` wrapper to allow mutually exclusive runtime computations (#382).
- [x] Expand runtime support in the `cbench-v1` dataset to use all 20 datasets for each benchmark.
- [ ] Expand runtime support in the `cbench-v1` dataset from 17 benchmarks to all 22.
- [x] Add an example of autotuning LLVM for runtime in the `examples` directory (#386).
