### ISSUE TITLE
Add support for optimizing GCC command line flags

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#383]
This issue tracks progress on merging @hughleat's new GCC environment into CompilerGym.

### Progress

- [x] Merge initial implementation (#314).
- [x] Add a "GCC Environment Reference" document to the [docs](https://facebookresearch.github.io/CompilerGym/).
- [ ] Complete the new action space schema (#369).
- [ ] Extend the [microbenchmark suite](https://github.com/facebookresearch/CompilerGym/blob/development/benchmarks/bench_test.py) to GCC.
- [ ] Port GCC action space to the new schema to expose a Tuple / Dict space with all options set by a single action.
- [ ] Complete the new multi-file Benchmark proto schema (#325).
- [ ] Use multi-file Benchmarks to enable the GCC service to accept as a benchmark a set of files, not a single pre-processed source.
