### ISSUE TITLE
Add support for building CompilerGym using CMake

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#506]
## 🚀 Feature

This is a tracking issue for the progress that @KyleHerndon and @sogartar have made on adding support for building CompilerGym using CMake.

The initial discussions and plan were outlined in the comments of this PR #478.

Progress:

- [x] Support for building the CompilerGym wheel on Linux (#498)
- [ ] Support for building the CompilerGym wheel on macOS
- [ ] Support for building `examples/`
- [ ] Support for building `benchmarks/`
- [ ] Resolve the `TODO(github.com/facebookresearch/CompilerGym/issues/506)` issues in the source.
- [ ] Speed up the build, especially the CI job (#595)
- [ ] Rewrite the CMakeLists files to use more idiomatic CMake style

**Comment by ChrisCummins** [comment]
General question for @sogartar and @KyleHerndon, is it on your roadmap to add macOS support to the CMake build?

Cheers,
Chris

**Comment by sogartar** [comment]
> General question for @sogartar and @KyleHerndon, is it on your roadmap to add macOS support to the CMake build?

@ChrisCummins, we are planing to add it after we add the MLIR env. So it will be in a few weeks.
There is also the examples and benchmarks that are not yet buildable with CMake that we have to address.

**Comment by ChrisCummins** [comment]
Awesome, thanks! I'll add a progress list to this task. I don't think the examples or benchmarks directories will be too challenging as they don't have a lot of compiled code

Cheers,
Chris

**Comment by ChrisCummins** [comment]
@sogartar, is it possible to configure the CMake build to use a local copy of LLVM? Let's say I have a fork of LLVM and have arranged it with the following directory:

```sh
~/llvm/build  # cmake build dir
~/llvm/src  # sources
~/llvm/install  # install target
~/CompilerGym  # CompilerGym
```

From looking through the CMake configs it looks like the only control I have over the LLVM version used is `-DCOMPILER_GYM_LLVM_PROVIDER=external`, though even then it downloads and uses the v10.0.0 sources, and I'm not sure how it locates the binaries / libs. Sorry for the n00by CMake questions, I'm still getting up to speed with it :-)

Cheers,
Chris

**Comment by ChrisCummins** [comment]
The use cases I would like to support with this are:

- The user has a local fork of LLVM that they want to build the CompilerGym environment against. The user should be able to pass the path of their local source and install directories and CompilerGym will build against it.
- The user wants to download and build against LLVM's binary and source release archives. This is equivalent to how the Bazel build works, and would enable the user to build CompilerGym without having to compile LLVM from scratch (this could be the default for CI jobs to make the CMake build the default).
- The user wants the CompilerGym to build LLVM from source (as is the default now), but using a different version of LLVM, and controlling some of the LLVM build options. E.g. `cmake ... -DLLVM_SRCS=https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-12.0.1.tar.gz -DCMAKE_BUILD_TYPE=Release`.

I'm happy to help contribute towards this if you give me a couple of pointers on how to start.

**Comment by sogartar** [comment]
The `DCOMPILER_GYM_LLVM_PROVIDER=external` option is not tested yet, but it is supposed to only find a preinstalled LLVM without building it. If it is not installed in a default location like `/usr/local` then the path should be provided according to the specifics of [find_package(...)](https://cmake.org/cmake/help/latest/command/find_package.html) for LLVM. Usually you can do that by specifying [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/latest/envvar/CMAKE_PREFIX_PATH.html#envvar:CMAKE_PREFIX_PATH) or PackageName_DIR for a specific package. For example `LLVM_DIR`.
```
cmake -D LLVM_DIR=/path/to/llvm/install ...
```
Some packages provide custom `find_package` logic that may have other ways of customizing the search paths, but usually they try to stick to these variables.

Currently there is no way to specify an external LLVM source to be included in the super-build. I see now that this may be a problem, since we need the LLVM source code also during the build, which may crate a mismatch of versions. This piece would need refactoring.

**Comment by ChrisCummins** [comment]
> The `DCOMPILER_GYM_LLVM_PROVIDER=external` option is not tested yet, but it is supposed to only find a preinstalled LLVM without building it. If it is not installed in a default location like `/usr/local` then the path should be provided according to the specifics of `[find_package(...)](https://cmake.org/cmake/help/latest/command/find_package.html)` for LLVM. Usually you can do that by specifying [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/latest/envvar/CMAKE_PREFIX_PATH.html#envvar:CMAKE_PREFIX_PATH) or _DIR for a specific package. For example `LLVM_DIR`.
> 
> ```
> cmake -D LLVM_DIR=/path/to/llvm/install ...
> ```
> 
> Some packages provide custom `find_package` logic that may have other ways of customizing the search paths, but usually they try to stick to these variables.

Thanks for the details. I have tried:

```sh
$ cmake ... -DCOMPILER_GYM_LLVM_PROVIDER=external -DLLVM_DIR=/path/to/my/llvm
```

But I found that `LLVM_DIR` was still set to `build/external/...`. I'll dig into this a bit and let you know what I find.

> Currently there is no way to specify an external LLVM source to be included in the super-build. I see now that this may be a problem, since we need the LLVM source code also during the build, which may crate a mismatch of versions. This piece would need refactoring.

The LLVM sources are only needed by the scripts in [this dir](https://github.com/facebookresearch/CompilerGym/tree/development/compiler_gym/envs/llvm/service/passes) to extract the list of passes and generate a couple of .h/.py files. One workaround could be to split this out from the regular build by committing the generated files for whatever version of LLVM we build against. That way we don't need the LLVM sources, and users could run these scripts to generate their own files against a different version of LLVM should they wish (cf #568).

Cheers,
Chris

**Comment by sogartar** [comment]
> Thanks for the details. I have tried:
> 
> ```shell
> $ cmake ... -DCOMPILER_GYM_LLVM_PROVIDER=external -DLLVM_DIR=/path/to/my/llvm
> ```
> 
> But I found that `LLVM_DIR` was still set to `build/external/...`. I'll dig into this a bit and let you know what I find.

According to https://llvm.org/docs/CMake.html `LLVM_CMAKE_DIR` is the variable to use.

**Comment by sogartar** [comment]
> Thanks for the details. I have tried:
> 
> ```shell
> $ cmake ... -DCOMPILER_GYM_LLVM_PROVIDER=external -DLLVM_DIR=/path/to/my/llvm
> ```
> 
> But I found that `LLVM_DIR` was still set to `build/external/...`. I'll dig into this a bit and let you know what I find.

There may be some other problem but according to https://llvm.org/docs/CMake.html `LLVM_DIR` is the variable to use.

**Comment by sogartar** [comment]
In [build_external_cmake_project](https://github.com/facebookresearch/CompilerGym/blob/11784d436fc9bd4c3d9a1588508a970649ac5ed3/build_tools/cmake/build_external_cmake_project.cmake#L51) the install dir is added to `CMAKE_PREFIX_PATH`. Although I doubt it, but it may take precedence over `LLVM_DIR`.

**Comment by ChrisCummins** [comment]
Thanks. I was able to fix this by replacing [this](https://github.com/facebookresearch/CompilerGym/blob/development/external/external.cmake#L113-L122) with just:

```
find_package(LLVM REQUIRED CONFIG)
```

I'm working on a conditional if/else block depending on COMPILER_GYM_LLVM_PROVIDER like [here](https://github.com/facebookresearch/CompilerGym/blob/development/external/external.cmake#L103) but am still figuring out how cmake works :) There are some other issues like conflicting gtest definitions.

Cheers,
Chris

**Comment by ChrisCummins** [comment]
@sogartar, @kylescotshank, @mostafaelhoushi, I've created a [new project](https://github.com/facebookresearch/CompilerGym/projects/3) to track the various tasks needed to fully migrate from Bazel to CMake. I'll split the list of tasks here into individual issues that can be tracked and discussed separately.

Closing this in favor of tracking progress on the project page.

Cheers,
Chris
