### ISSUE TITLE
Add support for building LLVM environment against different versions of LLVM

### ISSUE THREAD

**Issue by ChrisCummins** [facebookresearch/CompilerGym#568]
## 🚀 Feature

The CompilerGym LLVM environment is deeply integrated with the LLVM sources and is currently built against version 10.0.0. We would like to add support for more versions of LLVM.

## Motivation

There are two main categories of users that we want to address:

- *Support for folks who use a newer/older version of LLVM:* Not everyone uses LLVM 10.0.0.
- *Support for folks who use a modified of LLVM:* It is quite common for people to fork LLVM and maintain a set of downstream patches. For those users, we should support the ability to build against their local copy of LLVM. The user should be able to pass the path of their local install directory and CompilerGym will build against it.

## Pitch

Split this task into two stages:

1. Add support for building the CompilerGym LLVM environment against a different version of LLVM. Support only CMake build (cf #506), and allow the LLVM version to be built against to be specified at the configuration stage.
2. Enable multiple LLVM environments to co-exist in the same build, and add an API to enable them to  selected from at runtime, e.g.
```py
>>> import compiler_gym
>>> env = compiler_gym.make("llvm-v0", llvm_version="10.0.0")
>>> env = compiler_gym.make("llvm-v0", llvm_version="13.0.1")
```

## Alternatives

Don't change the existing LLVM environment, but add a new "shallow integration" environment that wraps the LLVM command line, enabling multiple versions of LLVM to be support. Similar to @hughleat's implementation of the GCC environment.

## Additional context

Having spent a couple of days hacking on this, here are the pain points that I've identified so far:

- [ ] Changing the version of LLVM used currently requires hardcoding the change in the `CMakeLists.txt` files in two places. See example [here](https://github.com/ChrisCummins/CompilerGym/commit/d36ed54685a96e5f5834419eb27c697d462de431). This should be possible through the command line during cmake's configuration step.
- [ ] The CompilerGym build requires access to the LLVM sources so that it can extract a list of passes to construct the action space from (implementation [here](https://github.com/facebookresearch/CompilerGym/tree/11784d436fc9bd4c3d9a1588508a970649ac5ed3/compiler_gym/envs/llvm/service/passes)). We want to enable LLVM builds where there isn't access to the original sources. This means providing pre-generated action space sources for different LLVM versions, and supplying the script so that users can generate the sources from their own copy of LLVM should they wish.
- [ ] The LLVM environment requires access to various LLVM binaries such as clang, lli, llvm-size, etc. Rather than fetching those during build time, it [is hardcoded to download a pack of files for LLVM 10](https://github.com/facebookresearch/CompilerGym/blob/11784d436fc9bd4c3d9a1588508a970649ac5ed3/compiler_gym/third_party/llvm/__init__.py#L22-L89) at runtime. The reason for this is to keep the size of the CompilerGym wheel below the maximum size allowed on PyPi. Once we can get the size limit increased (https://github.com/pypa/pypi-support/issues/1665) this can be fixed.
- [ ] [ProGraML](https://github.com/ChrisCummins/ProGraML) is built against LLVM-10 using an external [bazel build step](https://github.com/facebookresearch/CompilerGym/blob/22ac8444ae7e0d589f6d2cee3a84159132b2adf7/external/programl/CMakeLists.txt#L25-L48). We need to modify the ProGraML build to use the same version of LLVM as CompilerGym. The best way to do this may be to replace ProGraML's bazel build with a CMake config.
- [ ] The [logic for extracting the list of passes from LLVM](https://github.com/facebookresearch/CompilerGym/blob/11784d436fc9bd4c3d9a1588508a970649ac5ed3/compiler_gym/envs/llvm/service/passes/extract_passes_from_llvm_source_tree.py#L41-L232) is very fragile and doesn't adapt well to changes in LLVM version. This may need rethinking.
- [ ] The LLVM environment is based on the legacy pass pipeline API. As of version 14, this is deprecated (cf #558). This isn't blocking, but is something we should take a look at.
- [ ] To build against a locally installed copy of LLVM, you need to remove the gtest project definition as it conflicts the one set by LLVM.
- [ ] Enable the list of LLVM pass initializers to be generated programmatically (#573).
- [ ] LLVM paths are defined at module level (#571).
- [ ] Some of the datasets are distributed as bitcodes, which means that only 10.0.0 support is guaranteed. We need a mechanism to register a dataset as compatible with only certain LLVM versions.

## Related Work
- #558 
- #506

**Comment by ChrisCummins** [comment]
cc @sogartar, @KyleHerndon, some of this may be relevant to the work that you folks are doing. I have a branch, [feature/llvm-13](https://github.com/ChrisCummins/CompilerGym/tree/feature/llvm-13), which contains quick-and-dirty workarounds to the above problems for *only* LLVM 13. If you are working on similar things then let me know so we can coordinate :)

Cheers,
Chris

**Comment by sogartar** [comment]
@ChrisCummins, on the MLIR env that we are working the handling of the multiple LLVM versions is not ideal. In it only one of the MLIR or LLVM envs can be enabled and by extension only one LLVM version exists at a time.
The problem with having multiple version of LLVM in one CMake configuration is the collision of targets. I don't know if there is any way to give custom prefix of targets with `find_package(...)`. If we can't handle this well then the different LLVM versions would have to live in different CMake configurations. This is pretty bad, because it would drive also the targets that depend on them to live in different configurations. Writing custom find package logic for LLVM would be difficult due to the size of the LLVM project.

**Comment by ChrisCummins** [comment]
Ah I see, that's a shame, that kind of thing is totally trivial in Bazel with workspace scopes. Okay, let's not worry about for now :) To begin with, we focus on supporting a single version of LLVM at a time. Use v10.0.0 for the public release, and devs can build from source against a different LLVM should they wish.

Cheers,
Chris

**Comment by sogartar** [comment]
[This answer](https://stackoverflow.com/a/58336217/324204) hints of a solution, but cache variables may be a problem. The cache is shared.
Non-cache variables are fine because CMake has dynamic function scoping. Also targets defined in `find_package` usually have local source directory scope. `add_subdirectory` creates a new directory scope.

**Comment by Wuyoo0203** [comment]
Hi, I am currently working on replacing the llvm version to local llvm16. Is there any new progress in this work?
